set clk_name clk
set clk_port_name clk
set clk_period 2.5

# pervasive
puts "Setting false paths for pervasive inputs..."
set_false_path -from abst_scan_in
set_false_path -from an_ac_lbist_en_dc
set_false_path -from bcfg_scan_in
set_false_path -from ccfg_scan_in
set_false_path -from dcfg_scan_in
set_false_path -from func_scan_in
set_false_path -from gptr_scan_in
set_false_path -from pc_fu_abist_di_0
set_false_path -from pc_fu_abist_di_1
set_false_path -from pc_fu_abist_ena_dc
set_false_path -from pc_fu_abist_grf_renb_0
set_false_path -from pc_fu_abist_grf_renb_1
set_false_path -from pc_fu_abist_grf_wenb_0
set_false_path -from pc_fu_abist_raddr_0
set_false_path -from pc_fu_abist_raddr_1
set_false_path -from pc_fu_abist_raw_dc_b
set_false_path -from pc_fu_abist_waddr_0
set_false_path -from pc_fu_abist_waddr_1
set_false_path -from pc_fu_abist_wl144_comp_ena
set_false_path -from pc_fu_abst_sl_thold_3
set_false_path -from pc_fu_abst_slp_sl_thold_3
set_false_path -from pc_fu_ary_nsl_thold_3
set_false_path -from pc_fu_ary_slp_nsl_thold_3
set_false_path -from pc_fu_ccflush_dc
set_false_path -from pc_fu_cfg_sl_thold_3
set_false_path -from pc_fu_cfg_slp_sl_thold_3
set_false_path -from pc_fu_fce_3
set_false_path -from pc_fu_func_nsl_thold_3
set_false_path -from pc_fu_func_sl_thold_3
set_false_path -from pc_fu_func_slp_nsl_thold_3
set_false_path -from pc_fu_func_slp_sl_thold_3
set_false_path -from pc_fu_gptr_sl_thold_3
set_false_path -from pc_fu_repr_sl_thold_3
set_false_path -from pc_fu_sg_3
set_false_path -from pc_fu_time_sl_thold_3
set_false_path -from pc_fu_trace_bus_enable
set_false_path -from pc_fu_event_bus_enable
set_false_path -from pc_fu_instr_trace_mode
set_false_path -from pc_fu_instr_trace_tid
set_false_path -from repr_scan_in
set_false_path -from tc_ac_scan_diag_dc
set_false_path -from tc_ac_scan_dis_dc_b
set_false_path -from time_scan_in
