set clk_name clk
set clk_port_name clk
set clk_period 2.5

# pervasive
puts "Setting false paths for pervasive inputs..."
set_false_path -from pc_lq_ccflush_dc
set_false_path -from pc_lq_gptr_sl_thold_3
set_false_path -from pc_lq_time_sl_thold_3
set_false_path -from pc_lq_repr_sl_thold_3
set_false_path -from pc_lq_bolt_sl_thold_3
set_false_path -from pc_lq_abst_sl_thold_3
set_false_path -from pc_lq_abst_slp_sl_thold_3
set_false_path -from pc_lq_func_sl_thold_3
set_false_path -from pc_lq_func_slp_sl_thold_3
set_false_path -from pc_lq_cfg_sl_thold_3
set_false_path -from pc_lq_cfg_slp_sl_thold_3
set_false_path -from pc_lq_regf_slp_sl_thold_3
set_false_path -from pc_lq_func_nsl_thold_3
set_false_path -from pc_lq_func_slp_nsl_thold_3
set_false_path -from pc_lq_ary_nsl_thold_3
set_false_path -from pc_lq_ary_slp_nsl_thold_3
set_false_path -from pc_lq_sg_3
set_false_path -from pc_lq_fce_3
set_false_path -from pc_lq_abist_wl64_comp_ena
set_false_path -from pc_lq_abist_g8t_wenb
set_false_path -from pc_lq_abist_g8t1p_renb_0
set_false_path -from pc_lq_abist_g8t_dcomp
set_false_path -from pc_lq_abist_g8t_bw_1
set_false_path -from pc_lq_abist_g8t_bw_0
set_false_path -from pc_lq_abist_di_0
set_false_path -from pc_lq_abist_waddr_0
set_false_path -from pc_lq_abist_ena_dc
set_false_path -from pc_lq_abist_raw_dc_b
set_false_path -from pc_lq_abist_g6t_bw
set_false_path -from pc_lq_abist_di_g6t_2r
set_false_path -from pc_lq_abist_wl256_comp_ena
set_false_path -from pc_lq_abist_dcomp_g6t_2r
set_false_path -from pc_lq_abist_raddr_0
set_false_path -from pc_lq_abist_g6t_r_wb
set_false_path -from pc_lq_bo_enable_3
set_false_path -from pc_lq_bo_unload
set_false_path -from pc_lq_bo_repair
set_false_path -from pc_lq_bo_reset
set_false_path -from pc_lq_bo_shdata
set_false_path -from pc_lq_bo_select
set_false_path -from an_ac_lbist_ary_wrt_thru_dc
set_false_path -from an_ac_scan_dis_dc_b
set_false_path -from an_ac_scan_diag_dc
set_false_path -from an_ac_lbist_en_dc
set_false_path -from an_ac_atpg_en_dc
set_false_path -from an_ac_grffence_en_dc
set_false_path -from gptr_scan_in
set_false_path -from abst_scan_in
set_false_path -from time_scan_in
set_false_path -from repr_scan_in
set_false_path -from regf_scan_in
set_false_path -from ccfg_scan_in
set_false_path -from func_scan_in
