// Generated by gdsDummy       18/10/2022 21:53:38

module tri_fu_mul (
 inout                 vdd,
 inout                 gnd,
 input                 clk,
 input                 rst,
 input                 clkoff_b,
 input                 act_dis,
 input                 flush,
 input                 delay_lclkr,
 input                 mpw1_b,
 input                 mpw2_b,
 input                 sg_1,
 input                 thold_1,
 input                 fpu_enable,
 input                 f_mul_si,
 output                f_mul_so,
 input                 ex2_act,
 input  [0:52]         f_fmt_ex2_a_frac,
 input                 f_fmt_ex2_a_frac_17,
 input                 f_fmt_ex2_a_frac_35,
 input  [0:53]         f_fmt_ex2_c_frac,
 output [1:108]        f_mul_ex3_sum,
 output [1:108]        f_mul_ex3_car
);
endmodule
