// Generated by gdsDummy       10/11/2022 09:37:53

module toysram_16x12 (
 input  [0:15]         RWL0,
 input  [0:15]         RWL1,
 input  [0:15]         WWL,
 output [0:11]         RBL0,
 output [0:11]         RBL1,
 input  [0:11]         WBL,
 input  [0:11]         WBLb
);
endmodule
